name: todo_list_provider
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  sqflite: ^2.2.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter_overlay_loader: ^2.0.0
  path: ^1.8.2
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  validatorless: ^1.2.3
  google_sign_in: ^6.1.0
  
  flutter_signin_button: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: TodoListIcons
    - fonts:
      - asset: assets/fonts/TodoListIcons.ttf